fix(cache): prevent using invalid response from cache
unjs/nitro pull request #271
Opened 2022-06-08 15:58 UTC by clarkdo

### 🔗 Linked issue

https://github.com/nuxt/framework/issues/5328

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)

### 📚 Description

Resolves https://github.com/nuxt/framework/issues/5328

When cache is expired and multiple request come in at the same time, 1st request is pending at the handler, then 2nd request will reuse invalid response from previous expired value and 404 response may be returned.

This pr is fixing the invalid cached response by removing previous response value before handler is called.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2022-06-08 20:43 UTC, pi0 commented on src/runtime/cache.ts
> +        delete entry.value
```suggestion
        entry.value = undefined
```
```suggestion
        delete entry.value
```

2022-06-08 20:43 UTC, pi0 commented on src/runtime/cache.ts
> +        delete entry.value
```suggestion
        entry.value = undefined
```
```suggestion
        delete entry.value
```

2022-06-09 09:37 UTC, clarkdo commented on src/runtime/cache.ts
> +        delete entry.value
Thanks, is this OK to be merged ?

2022-06-12 21:31 UTC, pi0 requested changes
Thanks <3

2022-06-12 21:31 UTC, pi0 approved these changes

2022-06-12 21:32 UTC, merged