fix: unable to handle non-GET request in cloudflare page
unjs/nitro pull request #796
Opened 2023-01-03 00:32 UTC by DanSnow

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18ST3wMTcSFCK9MYDPbXW9YPWXi3Zn00%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=kE2uAWh)

### 🔗 Linked issue

#497
#787

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fix an issue that nitro won't be able to handle POST, PUT, etc requests on the Cloudflare page

Resolves #497 #787

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-01-03 21:04 UTC, Plinpod commented
When making these changes, I was able to get 200 responses for the API call however, the server API code never actually get executed. Have you run into that?

2023-01-04 09:36 UTC, DaniFoldi commented
👋 Hi,

Thanks for creating the PR to fix this - however I'm not sure if the approach you have taken is the one that should be used going forward. Pages will still invoke a Function for static assets, which defeats the purpose of using Pages, so instead, we should take advantage of their internal static asset handling.

For more context please see my comment [here](https://github.com/unjs/nitro/issues/497#issuecomment-1370686485)

2023-02-20 15:53 UTC, danielroe requested changes
I agree with @DaniFoldi that we need to do more than this, but regardless will still need to merge this to handle assets that are not prefixed or known in advance. The bug linked is caused by the fact that we shouldn't be getting assets by anything other than a GET request anyway so it may be better to add a condition.

Linking related PR to avoid hitting function for prefixed assets: https://github.com/unjs/nitro/pull/965

2023-02-20 15:53 UTC, danielroe commented on src/runtime/entries/cloudflare-pages.ts
>      const asset = await ctx.next();
```suggestion
    if (ctx.request.method === "GET") {
      const asset = await ctx.next();
```

2023-02-20 15:53 UTC, danielroe commented on src/runtime/entries/cloudflare-pages.ts
>      }
```suggestion
      if (asset.status !== 404) {
        return asset;
      }
    }
```

2023-02-21 12:38 UTC, closed without merging